version: '3.7'
services:
  postgres:
    image: postgres:10.5
    restart: always
    container_name: e-commercedb
    environment:
      - POSTGRES_USER=elcproduct
      - POSTGRES_PASSWORD=elcproduct!@#
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: