spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: "XXXXXX"
            clientSecret: "XXXXXX"
            redirectUri: "{baseUrl}/login/oauth2/code/{registrationId}"
            clientName: "Google"
            scope:
              - email
              - profile
              - email
              - address
              - phone
