spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/e_commerce?stringtype=unspecified
    username: elcproduct
    password: elcproduct!@#

  jpa:
    open-in-view: false
    show-sql: true
#    properties:
#      hibernate:
#        hbm2ddl:
#          auto: update
#      #        default_schema: elcproduct
#      schema: elcproduct

  liquibase:
    enabled: true
    liquibase-schema: e_commerce
